name: Mirror HPS Blog (Crawler)

on:
  schedule:
    - cron: "0 * * * *"   # hourly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crawl site
        env:
          START_URL: ${{ secrets.START_URL }}
          ARCHIVE_URL: ${{ secrets.ARCHIVE_URL }}
          ALLOWED_DOMAINS: ${{ secrets.ALLOWED_DOMAINS }}
          MAX_PAGES: "2000"
          REQUEST_DELAY: "0.8"
        run: python scripts/crawl.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: update blog mirror $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes"
          fi
